// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace back.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Alimentos"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Juguetes"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Accesorios"
                        });
                });

            modelBuilder.Entity("Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Imagen = "croquetas.png",
                            Nombre = "Croquetas CroqDog 5kg",
                            Precio = 350.00m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 1,
                            Imagen = "sobre.png",
                            Nombre = "Sobre Gourmet Gato",
                            Precio = 25.50m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 2,
                            Imagen = "pelota.png",
                            Nombre = "Pelota de Goma Chillona",
                            Precio = 80.00m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 2,
                            Imagen = "raton.png",
                            Nombre = "Ratón con Plumas",
                            Precio = 45.00m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 3,
                            Imagen = "correa.png",
                            Nombre = "Collar Antipulgas",
                            Precio = 120.00m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 6,
                            CategoriaId = 3,
                            Imagen = "cama.png",
                            Nombre = "Cama Acolchonada Grande",
                            Precio = 450.00m,
                            Stock = 5
                        });
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Producto", b =>
                {
                    b.HasOne("Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });
#pragma warning restore 612, 618
        }
    }
}
